-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 09:48:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Historico_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico_Produto` (
  `id_historico_produto` INT NOT NULL,
  `nome_produto` VARCHAR(45) NULL,
  `estoque_produto` INT NULL,
  `material_produto` VARCHAR(45) NULL,
  `dimensoes_produto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_historico_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preco` (
  `id_preco` INT NOT NULL,
  `preco_venda` FLOAT NULL,
  `preco_custo` FLOAT NULL,
  `data_alteracao` DATE NULL,
  `fk_id_historico_produto` INT NOT NULL,
  PRIMARY KEY (`id_preco`),
  INDEX `fk_id_produto_idx` (`fk_id_historico_produto` ASC),
  CONSTRAINT `fk_id_produto`
    FOREIGN KEY (`fk_id_historico_produto`)
    REFERENCES `mydb`.`Historico_Produto` (`id_historico_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `id_fornecedor` INT NOT NULL,
  `nome_fornecedor` VARCHAR(50) NULL,
  `cnpj_fornecedor` CHAR(18) NULL,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relacao_Fornecedor_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relacao_Fornecedor_Produto` (
  `fk_id_produto` INT NOT NULL,
  `fk_id_fornecedor` INT NOT NULL,
  INDEX `fk_id_fornecedor_idx` (`fk_id_fornecedor` ASC, `fk_id_produto` ASC),
  INDEX `fk_id_produto_idx` (`fk_id_produto` ASC),
  CONSTRAINT `fk_id_fornecedor`
    FOREIGN KEY (`fk_id_fornecedor` , `fk_id_produto`)
    REFERENCES `mydb`.`Fornecedor` (`id_fornecedor` , `id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_produto`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `mydb`.`Historico_Produto` (`id_historico_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Controle_Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Controle_Entrada` (
  `id_controle_entrada` INT NOT NULL,
  `data_entrada` DATE NULL,
  `quantidade_entrada` INT NULL,
  `fk_id_historico_produto` INT NOT NULL,
  PRIMARY KEY (`id_controle_entrada`),
  INDEX `fk_id_produto_idx` (`fk_id_historico_produto` ASC),
  CONSTRAINT `fk_id_produto`
    FOREIGN KEY (`fk_id_historico_produto`)
    REFERENCES `mydb`.`Historico_Produto` (`id_historico_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor_Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor_Contato` (
  `id_fornecedor_contato` INT NOT NULL,
  `email` VARCHAR(75) NULL,
  `telefone` VARCHAR(15) NULL,
  `fk_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_fornecedor_contato`),
  INDEX `fk_id_fornecedor_idx` (`fk_id_fornecedor` ASC),
  CONSTRAINT `fk_id_fornecedor`
    FOREIGN KEY (`fk_id_fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor_Endereco` (
  `id_fornecedor_endereco` INT NOT NULL,
  `cidade` VARCHAR(50) NULL,
  `bairro` VARCHAR(50) NULL,
  `rua` VARCHAR(70) NULL,
  `numero` INT NULL,
  `fk_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_fornecedor_endereco`),
  INDEX `fk_id_fornecedor_idx` (`fk_id_fornecedor` ASC),
  CONSTRAINT `fk_id_fornecedor`
    FOREIGN KEY (`fk_id_fornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_Venda` (
  `id_produto_venda` INT NOT NULL,
  `preco_venda` FLOAT NULL,
  `quantidade` INT NULL,
  `fk_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_produto_venda`),
  INDEX `fk_id_produto_idx` (`fk_id_produto` ASC),
  CONSTRAINT `fk_id_produto`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `mydb`.`Historico_Produto` (`id_historico_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `cargo_usuario` VARCHAR(20) NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  `cpf_usuario` CHAR(14) NULL,
  `nome_usuario` VARCHAR(50) NULL,
  `nascimento_usuario` DATE NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `id_venda` INT NOT NULL,
  `data_venda` DATE NULL,
  `preco_total_venda` FLOAT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_id_usuario_idx` (`fk_id_usuario` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relacao_Produto_Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relacao_Produto_Venda` (
  `id_relacao_prod_vend` INT NOT NULL,
  `fk_id_venda` INT NULL,
  `fk_id_produto_venda` INT NULL,
  PRIMARY KEY (`id_relacao_prod_vend`),
  INDEX `fk_id_venda_idx` (`fk_id_venda` ASC),
  INDEX `fk_id_produto_venda_idx` (`fk_id_produto_venda` ASC),
  CONSTRAINT `fk_id_venda`
    FOREIGN KEY (`fk_id_venda`)
    REFERENCES `mydb`.`Venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_produto_venda`
    FOREIGN KEY (`fk_id_produto_venda`)
    REFERENCES `mydb`.`Produto_Venda` (`id_produto_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_Contato` (
  `id_usuario_contato` INT NOT NULL,
  `email` VARCHAR(70) NULL,
  `telefone` VARCHAR(15) NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario_contato`),
  INDEX `fk_id_usuario_idx` (`fk_id_usuario` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_Endereco` (
  `id_usuario_endereco` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(70) NULL,
  `numero` INT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario_endereco`),
  INDEX `fk_id_usuario_idx` (`fk_id_usuario` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id_historico_produto` INT NOT NULL,
  `nome_produto` VARCHAR(45) NULL,
  `estoque_produto` VARCHAR(45) NULL,
  `material_produto` VARCHAR(45) NULL,
  `dimensoes_produto` VARCHAR(45) NULL,
  `fk_id_historico_produto` INT NOT NULL,
  PRIMARY KEY (`id_historico_produto`),
  INDEX `fk_id_historico_produto_idx` (`fk_id_historico_produto` ASC),
  CONSTRAINT `fk_id_historico_produto`
    FOREIGN KEY (`fk_id_historico_produto`)
    REFERENCES `mydb`.`Historico_Produto` (`id_historico_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
